stages:
    - build
    - test

build laptop:
    image: alpine
    stage: build
    script: 
        - echo "Building a laptop"
        - mkdir build
        - chmod +x build
        - touch build/computer.txt
        - echo "Mainboard" >> build/computer.txt
        - cat build/computer.txt
        - echo "Keyboard" >> build/computer.txt
    artifacts:
        paths:
            - build
       
test laptop:
    image: alpine
    stage: test
    script:
        - test -f build/computer.txt
        - grep "Mainboard" build/computer.txt
        - grep "Keyboard" build/computer.txt
